### ISSUE TITLE
Error MSB4018: The "PublicizeTask" task failed unexpectedly. Could not load file System.Text.Json

### ISSUE THREAD

**Issue by MSchmoecker** [BepInEx/BepInEx.AssemblyPublicizer#10]
While trying to switch to this package, an error is thrown:

> /home/runner/.nuget/packages/bepinex.assemblypublicizer.msbuild/0.4.1/build/BepInEx.AssemblyPublicizer.MSBuild.props(11,9): error MSB4018: The "PublicizeTask" task failed unexpectedly. [/home/runner/work/Jotunn/Jotunn/JotunnLib/JotunnLib.csproj]
/home/runner/.nuget/packages/bepinex.assemblypublicizer.msbuild/0.4.1/build/BepInEx.AssemblyPublicizer.MSBuild.props(11,9): error MSB4018: System.TypeLoadException: Could not load type of field 'AsmResolver.DotNet.Config.Json.RuntimeOptions:<ConfigProperties>k__BackingField' (0) due to: Could not load file or assembly 'System.Text.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. [/home/runner/work/Jotunn/Jotunn/JotunnLib/JotunnLib.csproj]

The full log can be seen [here](https://github.com/MSchmoecker/Jotunn/actions/runs/7323970534/job/19947084628).

What I already tried:
- bumped the project (Jotunn) from net462 to net472
- Reference System.Text.Json 6.0.0
- Reference AsmResolver.DotNet 5.0.0 (and removing System.Text.Json because it's managed by AsmResolver.DotNet)

Any insight would be great, this publicizer would make the development much more seemless.

**Comment by js6pak** [comment]
This is likely the same issue as #11, could you try switching to the modern SDK-style project format?

**Comment by MSchmoecker** [comment]
The main project is using the SDK style project https://github.com/MSchmoecker/Jotunn/blob/dev/JotunnLib/JotunnLib.csproj and the project compiles locally without any issues.

Two projects inside the solution were using the legacy csproj format. However, even after removing all other project from the solution and updating to 0.4.2, the same error occurs https://github.com/MSchmoecker/Jotunn/actions/runs/8375446996/job/22932800248

**Comment by js6pak** [comment]
You are calling `msbuild` on linux which is aliased to mono's [`xbuild`](https://www.mono-project.com/archived/xbuild/) which has been dead for a very long time, it's surprising that it runs with the new project format at all.
You should just use `dotnet build -c Release` instead, which uses the modern msbuild from the .NET (Core) SDK.

**Comment by MSchmoecker** [comment]
Thanks a lot, `dotnet build` works!

Mono is probably a leftover from the time when the project used MMHOOK instead of Harmony.
